// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ondcyheslxgqwigoxwrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZGN5aGVzbHhncXdpZ294d3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDc1MjMsImV4cCI6MjA2NTU4MzUyM30.yD4c6Razi3Zh_LQlkDQAFoyzKU1F4RsW7_Smq8I3-BY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);